public class Calculator {
    public static void addition(){
        Integer var1 = 5, var2 = 10, sum;
        sum = var1 + var2;
        system.debug(sum);
    }
     public static void subtraction(){
        Integer var1 = 5, var2 = 10, sub;
        sub = var1 - var2;
        system.debug(sub);
    }
     public static void multiplication(Integer var1, Integer var2){
        Integer mul;
        mul = var1 * var2;
        system.debug(mul);
    }

}